// Generated by CoffeeScript 1.4.0
(function() {

  $(document).ready(function() {
    var $input, canvas, chordAlternatives, ctx, currentAlternative, currentChord, drawChord, drawUnknown;
    canvas = document.getElementById('chord');
    ctx = canvas.getContext('2d');
    ctx.translate(0.5, 0.5);
    currentChord = "C";
    currentAlternative = 0;
    chordAlternatives = [];
    drawChord = function() {
      return ChordDrawer.drawChord(ctx, currentChord, chordAlternatives[currentAlternative]);
    };
    drawUnknown = function() {
      return ChordDrawer.drawUnknown(ctx);
    };
    $input = $("input#chord-input");
    $input.val(currentChord);
    $input.on("keyup change", function() {
      var chord;
      chord = $input.val();
      currentChord = chord;
      currentAlternative = 0;
      try {
        chordAlternatives = ChordGenerator.frets(chord);
        chordAlternatives = _(chordAlternatives).reject(function(alt) {
          return alt.length > 4;
        });
      } catch (e) {
        chordAlternatives = [];
      }
      if (chordAlternatives.length > 0) {
        return drawChord();
      } else {
        return drawUnknown();
      }
    });
    $input.change();
    $("a#prev-chord").on("click", function() {
      if (currentAlternative === 0) {
        currentAlternative = chordAlternatives.length;
      }
      currentAlternative -= 1;
      drawChord(chordAlternatives[currentAlternative]);
      return false;
    });
    return $("a#next-chord").on("click", function() {
      currentAlternative += 1;
      currentAlternative %= chordAlternatives.length;
      drawChord(chordAlternatives[currentAlternative]);
      return false;
    });
  });

}).call(this);
